name: CI
on:
  # We run the CI checks on any pull request updates or pushes to the main branch after PR merge.
  pull_request:
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version-file: 'go.mod'
          check-latest: true
      - run: |
          go vet ./...
          go test ./... --cover
      - name: Install license check tool
        run: go install github.com/google/addlicense@dc31ac9ffcca99c9457226366135701794b128c0
      - name: Check licenses
        run: addlicense -l apache -check -v -ignore '**/*.yaml' -c Humanitec ./loader ./schema ./types ./pkg
